globalHeaders:
  Content-Security-Policy: "default-src 'self' blob: data: https:;
    object-src 'self' blob:;
    frame-src 'self' https://*.microsoft.com https://*.powerplatform.com https://*.botframework.com https://*.virtualagents.microsoft.com;
    script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.microsoft.com https://*.powerplatform.com https://*.botframework.com;
    connect-src 'self' https://*.microsoft.com https://*.powerplatform.com https://*.botframework.com;"
